services:
  postgres:
    image: postgres:16
    container_name: logiflow-postgres
    environment:
      POSTGRES_USER: logiflow
      POSTGRES_PASSWORD: logiflow
      POSTGRES_DB: logiflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
